name: Run on Comment
on:
  issue_comment:
    types: [created, edited]

jobs:
  cropimage:
    runs-on: ubuntu-latest
#    if: github.event.issue.pull_request && contains(github.event.comment.body, '/hello')
    steps:
      - name: Get PR info
        id: pr_info
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            core.setOutput("sha", pr.data.head.sha);
            core.setOutput("ref", pr.data.head.ref);
            core.setOutput("repo", pr.data.head.repo.full_name);
      - name: Debug
        run: |
          echo "Event: ${{ toJson(github.event) }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Type: ${{ github.event.action }}"
          echo "Comment Body: ${{ github.event.comment.body }}"
          echo "Pull Request URL: ${{ github.event.issue.pull_request.url }}"
          echo "Pull Request Ref: ${{ pr_info.ref }}"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up Python
        run: |
          pip install Pillow
          pip install opencv-python
          pip install opencv-contrib-python
      - name: Gather changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            **.jpg
            **.jpeg
            **.png
            **.tif
            **.tiff

