name: Run on Comment
on:
  issue_comment:
    types: [created, edited]

jobs:
  cropimage:
    runs-on: ubuntu-latest
#    if: github.event.issue.pull_request && contains(github.event.comment.body, '/hello')
    steps:
      - name: Debug
        run: |
          echo "PR Number: ${{ github.event.issue.number }}"
          echo "Repo: ${{ github.repository }}"
          echo "Owner: ${{ github.repository_owner }}"
      - name: Get PR info
        id: pr_info
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: "${{ github.event.issue.number}}" ,
            });
            core.setOutput("sha", pr.data.head.sha);
            core.setOutput("ref", pr.data.head.ref);
            core.setOutput("repo", pr.data.head.repo.full_name);
      - name: Debug
        run: |        
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Type: ${{ github.event.action }}"
          echo "Comment Body: ${{ github.event.comment.body }}"
          echo "Pull Request URL: ${{ github.event.issue.pull_request.url }}"
          echo "PR: ${{ toJson(steps.pr_info) }}"
          echo "Pull Request Ref: ${{ steps.pr_info.outputs.ref }}"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.pr_info.outputs.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up Python
        run: |
          pip install Pillow
          pip install opencv-python
          pip install opencv-contrib-python
      - name: Gather changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            **.jpg
            **.jpeg
            **.png
            **.tif
            **.tiff
          files_ignore: |
            **thumbnail**
          fetch_depth: 1
      - name: Find Images With Wrong Orientation
        id: find-images
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
        run: |
          ALL_CHANGED_IMAGES=$(for image in `echo $ALL_CHANGED_FILES`; do
            if [[ $image == *.jpg || $image == *.jpeg || $image == *.png || $image == *.tif || $image == *.tiff ]]; then
              echo "$image"
            fi
          done)
          $GITHUB_WORKSPACE/.github/scripts/checkImageOrientation.py $ALL_CHANGED_IMAGES >> $GITHUB_OUTPUT
      - name: Correct Image Orientation
        id: correct-image-orientation
        if: ${{ steps.find-images.outputs.wrong_sized_images != '' }}
        run: |
          echo "The following images are not in the correct orientation:"
          echo "${{ steps.find-images.outputs.wrong_sized_images }}"
          $GITHUB_WORKSPACE/.github/scripts/imageCrop.py ${{ steps.find-images.outputs.wrong_sized_images }}
      - name: Commit and Push Changes
        if: ${{ steps.correct-image-orientation.outputs.wrong_sized_images != '' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ steps.find-images.outputs.wrong_sized_images }}
          git commit -m "[Bot]Correct image orientation"
          git push
