name: Run on Comment
on:
  issue_comment:
    types: [created, edited]

jobs:
  cropimage:
    runs-on: ubuntu-latest
#    if: github.event.issue.pull_request && contains(github.event.comment.body, '/hello')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Say hello
        run: |
          cat $GITHUB_WORKSPACE/README.md
